;             
CREATE USER IF NOT EXISTS "SA" SALT '96aca2a37886ccad' HASH '0dd0c0c6c9bb21d9c52bb2657457337bb95e63d76cea5335887aea9c5c8386da' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A8357FCE_56BC_4449_81D3_C89D93903B4A" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."PHONE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_A8357FCE_56BC_4449_81D3_C89D93903B4A" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_A8357FCE_56BC_4449_81D3_C89D93903B4A",
    "CITYCODE" VARCHAR(255),
    "CONTRYCODE" VARCHAR(255),
    "NUMBER" VARCHAR(255)
); 
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHONE;   
CREATE MEMORY TABLE "PUBLIC"."USUARIO"(
    "ID" BINARY NOT NULL,
    "CREATED" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "ISACTIVE" BOOLEAN NOT NULL,
    "LAST_LOGIN" TIMESTAMP,
    "MODIFIED" TIMESTAMP,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "TOKEN" VARCHAR(255)
);       
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO; 
CREATE MEMORY TABLE "PUBLIC"."USUARIO_PHONES"(
    "USUARIO_ID" BINARY NOT NULL,
    "PHONES_ID" BIGINT NOT NULL
);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO_PHONES;          
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."UK_5BQC1344TAX0V7W58423TMXXQ" UNIQUE("PHONES_ID");             
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."FK9IK11PUR6S258FGUR951UISWK" FOREIGN KEY("PHONES_ID") REFERENCES "PUBLIC"."PHONE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."USUARIO_PHONES" ADD CONSTRAINT "PUBLIC"."FKP1C8DTI15OU6BKMM9I6K6GE42" FOREIGN KEY("USUARIO_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;            
